augment: spec_augment
wavs_path: cleaned_tth_data/wavs
label_path: cleaned_tth_data/test.txt
feature: mfcc
npy_path: tth_test.npy

train_path: ravdess.npy
test_path: ravdess.npy

label:
  neutral: 0
  angry: 1
  happy: 2
  sad: 3
  calm: 4
  fearful: 5
  disgust: 6
  surprised: 7
audio:
  sample_rate: 48000

mfcc:
  hop_length: 256
  win_length: 1024
  n_mfcc: 39
  n_mels: 128
  fmax: 8000
  fmin: 40
