augment: spec_augment
wavs_path: cleaned_tth_data/wavs
label_path: cleaned_tth_data/train.txt
feature: mfcc
npy_path: tth_train.npy

train_path: tth_train_mfcc.npy
test_path: tth_test_mfcc.npy

define: &hidden_dim 39
hidden_dim: *hidden_dim

valid_size: 0.5

audio:
  sample_rate: 22050
  max_wav_value: 32768.0
stft:
  filter_length: 1024
  hop_length: 256
  win_length: 1024

mel:
  n_mel_channels: 80
  mel_fmin: 40
  mel_fmax: 8000

mfcc:
  n_mfcc: 39
  mel_fmin: 40
  mel_fmax: 8000

label:
  neutral: 0
  angry: 1
  happy: 2
  sad: 3